### ISSUE TITLE
how to configure netlify-cms-widget-mdx with NextJS ?

### ISSUE THREAD

**Issue by anishd19** [karolis-sh/gatsby-mdx#60]
I  am using Netlify CMS and Next JS. I am not sure where to inject the code 
```javascript 
import { MdxControl, MdxPreview } from 'netlify-cms-widget-mdx';
CMS.registerWidget('mdx', MdxControl, MdxPreview); 
```
Please tell me how to make this widget work with Next JS & Netlify CMS combination. Thanks.

**Comment by karolis-sh** [comment]
What have you tried? What errors you got?

https://www.netlifycms.org/docs/widgets/

```yml
```

**Comment by anishd19** [comment]
I am getting `ReferenceError: window is not defined` error on configuring this widget.

The issue is with the netlify-cms itself and not with this widget. I have created a new issue in the netlify-cms project. https://github.com/netlify/netlify-cms/issues/3580 . Thanks
